openapi: 3.1.0
info:
  title: Marketplace API
  version: 1.0.0
paths:
  /hello:
    get:
      summary: Get a greeting message
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Hello, world!